version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: django_project-nginx
    ports:
      - "80:80"
    volumes:
      - ./src/static:/static
      - ./src/media:/media
      - ./config/nginx-dev:/etc/nginx/conf.d
    depends_on:
      - django_project

  django_project:
    build: .
    #image: sod723/django_project:0.1
    container_name: django_project
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./scripts:/scripts
    # Dev user: admin pass: admin
    command: ["/scripts/wait-for-it.sh", "db:3306", "-t", "30", "--", "/scripts/command-dev.sh"]
    expose:
      - "8080"

  db:
    image: mysql:8
    container_name: django_project-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: django_project
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  portainer:
      image: portainer/portainer
      container_name: portainer
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

volumes:
  portainer_data:


