# Generated by Django 4.2.2 on 2023-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("a_no", models.AutoField(primary_key=True, serialize=False)),
                ("a_type", models.CharField(max_length=50)),
                ("a_title", models.CharField(max_length=255)),
                ("a_note", models.CharField(blank=True, max_length=4096, null=True)),
                ("a_image", models.CharField(blank=True, max_length=4096, null=True)),
                ("a_count", models.IntegerField()),
                ("a_datetime", models.DateTimeField(blank=True, null=True)),
                ("a_usage", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "album",
            },
        ),
    ]
