apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_DATABASE: ZGphbmdvX3Byb2plY3Q=  # Base64로 인코딩된 'django_project'
  MYSQL_PASSWORD: YWRtaW4=            # Base64로 인코딩된 'admin'
  MYSQL_ROOT_PASSWORD: YWRtaW4=       # Base64로 인코딩된 'admin'
  MYSQL_USER: YWRtaW4=                # Base64로 인코딩된 'admin'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MYSQL_DEFAULT_AUTH_PLUGIN: mysql_native_password
