apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
      - name: django-project-mysql
        image: mysql:8
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_USER
          - name: MYSQL_DEFAULT_AUTH_PLUGIN
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_DEFAULT_AUTH_PLUGIN
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
