apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-project-claim1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/str/django-project-claim1"
