apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: django-project-claim1
  name: django-project-claim1
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
