apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-claim2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/str/nginx-claim2"
