apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/str/portainer-data-pv"
